# Generated by Django 3.2.21 on 2023-09-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('user_deleted'), related_name='user_assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_assigned_tickets', to='ticketapp.team'),
        ),
    ]
