# Generated by Django 3.2.21 on 2023-10-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20230929_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_assigned_tickets', to='ticketapp.team'),
        ),
    ]
