# Generated by Django 3.2.21 on 2023-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_alter_profile_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
